name: Проверка качества кода

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  quality:
    name: Проверка качества
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Скачать код
      uses: actions/checkout@v4
    
    - name: 🐍 Установить Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: 📦 Установить инструменты
      run: |
        pip install flake8 pylint
    
    # Проверка на синтаксические ошибки и undefined names
    - name: 🔍 Flake8 - проверка синтаксиса
      run: |
        # Остановить сборку если есть синтаксические ошибки
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Предупреждения о сложности (не блокирует)
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      continue-on-error: true
    
    # Проверка размера файлов
    - name: 📏 Проверка размера файлов
      run: |
        echo "Проверка больших файлов (>500 строк):"
        find . -name "*.py" -type f -exec wc -l {} \; | awk '$1 > 500 {print "⚠️ БОЛЬШОЙ ФАЙЛ: "$2" ("$1" строк)"}'
    
    # Подсчет тестового покрытия
    - name: 📊 Статистика проекта
      run: |
        echo "==================================="
        echo "📊 СТАТИСТИКА ПРОЕКТА"
        echo "==================================="
        echo "Python файлы:"
        find . -name "*.py" -type f | wc -l
        echo ""
        echo "Всего строк кода:"
        find . -name "*.py" -type f -exec wc -l {} \; | awk '{sum+=$1} END {print sum}'
        echo ""
        echo "Тестовые файлы:"
        find . -name "test_*.py" -type f | wc -l
        echo "==================================="


