name: Автоматический деплой

# Запускать только при успешных тестах на main ветке
on:
  workflow_run:
    workflows: ["Автоматическое тестирование бота"]
    types:
      - completed
    branches: [main, master]

jobs:
  deploy:
    name: Деплой бота
    runs-on: ubuntu-latest
    # Деплоить ТОЛЬКО если тесты прошли
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: 📥 Скачать код
      uses: actions/checkout@v4
    
    - name: ✅ Тесты пройдены
      run: |
        echo "✅ Все тесты пройдены успешно!"
        echo "🚀 Готов к деплою..."
    
    # ВАРИАНТ 1: Деплой через SSH (если у вас есть сервер)
    # Раскомментируйте и настройте, если нужно
    # - name: 🚀 Деплой на сервер через SSH
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SERVER_HOST }}
    #     username: ${{ secrets.SERVER_USER }}
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     script: |
    #       cd /path/to/bot
    #       git pull
    #       pip install -r requirements.txt
    #       systemctl restart dianalisa-bot
    
    # ВАРИАНТ 2: Уведомление о готовности к деплою
    - name: 📢 Уведомление
      run: |
        echo "::notice::✅ Код протестирован и готов к деплою!"
        echo "::notice::Запустите деплой вручную или настройте автоматический."
    
    # ВАРИАНТ 3: Создать Release
    - name: 🎉 Создать релиз
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Изменения
          - Все тесты пройдены ✅
          - Готов к продакшену
        draft: false
        prerelease: false


