name: Автоматическое тестирование бота

# Когда запускать
on:
  push:
    branches: [ main, master, develop ]  # При push в эти ветки
  pull_request:
    branches: [ main, master ]  # При создании PR

# Задачи
jobs:
  test:
    name: Тестирование на Windows
    runs-on: windows-latest  # Windows, как у вас локально
    
    steps:
    # Шаг 1: Скачать код из репозитория
    - name: 📥 Скачать код
      uses: actions/checkout@v4
    
    # Шаг 2: Установить Python 3.13
    - name: 🐍 Установить Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'  # Кэшировать пакеты для скорости
    
    # Шаг 3: Установить зависимости
    - name: 📦 Установить зависимости
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Шаг 4: Создать .env файл для тестов (без реальных токенов)
    - name: 🔐 Создать тестовый .env
      run: |
        echo "BOT_TOKEN=test_token" > .env
        echo "PAYMENT_TOKEN=test_payment_token" >> .env
        echo "DATABASE_PATH=test_dianalisa_bot.db" >> .env
    
    # Шаг 5: Запустить тесты клавиатур
    - name: ⌨️ Тест создания клавиатур
      run: python test_all_buttons_auto.py
      continue-on-error: false  # Остановить если тесты провалились
    
    # Шаг 6: Запустить edge case тесты
    - name: 🔍 Тест edge cases
      run: python test_edge_cases.py
      continue-on-error: false
    
    # Шаг 7: Проверить импорты и синтаксис
    - name: ✅ Проверка синтаксиса
      run: |
        python -m py_compile bot.py
        python -m py_compile callbacks.py
        python -m py_compile database.py
        python -m py_compile keyboards.py
    
    # Шаг 8: Сохранить результаты тестов
    - name: 📊 Результаты тестов
      if: always()  # Всегда выполнять, даже если тесты провалились
      run: |
        echo "========================================" 
        echo "ТЕСТИРОВАНИЕ ЗАВЕРШЕНО"
        echo "========================================"
        echo "Проверьте логи выше для деталей"
    
    # Шаг 9: Уведомление при провале
    - name: ❌ Тесты провалились
      if: failure()
      run: |
        echo "::error::ТЕСТЫ НЕ ПРОШЛИ! Проверьте логи выше."
        echo "::error::Деплой заблокирован до исправления ошибок."
        exit 1
    
    # Шаг 10: Успешное завершение
    - name: ✅ Тесты пройдены
      if: success()
      run: |
        echo "::notice::Все тесты пройдены успешно!"
        echo "::notice::Код готов к деплою."


