name: Автоматическое тестирование бота

# Когда запускать
on:
  push:
    branches: [ main, master, develop ]  # При push в эти ветки
  pull_request:
    branches: [ main, master ]  # При создании PR

# Задачи
jobs:
  test:
    name: Тестирование на Windows
    runs-on: windows-latest  # Windows, как у вас локально
    
    steps:
    # Шаг 1: Скачать код из репозитория
    - name: 📥 Скачать код
      uses: actions/checkout@v4
    
    # Шаг 2: Установить Python 3.13
    - name: 🐍 Установить Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'  # Кэшировать пакеты для скорости
    
    # Шаг 3: Установить зависимости
    - name: 📦 Установить зависимости
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Шаг 4: Создать тестовый .env файл
    - name: 🔐 Создать тестовый .env
      run: |
        python -c "with open('.env', 'w', encoding='utf-8') as f: f.write('BOT_TOKEN=test_token_for_ci_cd\nADMIN_IDS=123456789\nDATABASE_PATH=test_bot.db\n')"
    
    # Шаг 5: Запустить базовые CI/CD тесты
    - name: ✅ Базовые тесты (синтаксис, импорты, структура)
      run: python test_ci_basic.py
      continue-on-error: false
    
    # Шаг 8: Сохранить результаты тестов
    - name: 📊 Результаты тестов
      if: always()  # Всегда выполнять, даже если тесты провалились
      run: |
        echo "========================================" 
        echo "ТЕСТИРОВАНИЕ ЗАВЕРШЕНО"
        echo "========================================"
        echo "Проверьте логи выше для деталей"
    
    # Шаг 9: Уведомление при провале
    - name: ❌ Тесты провалились
      if: failure()
      run: |
        echo "::error::ТЕСТЫ НЕ ПРОШЛИ! Проверьте логи выше."
        echo "::error::Деплой заблокирован до исправления ошибок."
        exit 1
    
    # Шаг 10: Успешное завершение
    - name: ✅ Тесты пройдены
      if: success()
      run: |
        echo "::notice::Все тесты пройдены успешно!"
        echo "::notice::Код готов к деплою."


